//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library.Mvc.Test.ProblemsDetails {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Library.Mvc.Test.ProblemsDetails.TestsResources", typeof(TestsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProblemDetailsResolver dans le cadre des TU.
        /// </summary>
        internal static string Tests_DefaultContextLabel {
            get {
                return ResourceManager.GetString("Tests.DefaultContextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;erreur 1 est survenue dans le cadre des TU.
        /// </summary>
        internal static string Tests_PE_TestProblem_ErreurGeneric1 {
            get {
                return ResourceManager.GetString("Tests_PE_TestProblem.ErreurGeneric1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;erreur 2 est survenue dans le cadre des TU.
        /// </summary>
        internal static string Tests_PE_TestProblem_ErreurGeneric2 {
            get {
                return ResourceManager.GetString("Tests_PE_TestProblem.ErreurGeneric2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail pour validation d&apos;un user dans le cadre des TU.
        /// </summary>
        internal static string Tests_VE_TestValidation_Detail {
            get {
                return ResourceManager.GetString("Tests_VE_TestValidation.Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titre pour validation d&apos;un user dans le cadre des TU.
        /// </summary>
        internal static string Tests_VE_TestValidation_Title {
            get {
                return ResourceManager.GetString("Tests_VE_TestValidation.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur 1 pour la propriété ne passant pas la validation.
        /// </summary>
        internal static string Tests_VE_TestValidation_User_Erreur1 {
            get {
                return ResourceManager.GetString("Tests_VE_TestValidation.User:Erreur1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur 2 pour la propriété ne passant pas la validation.
        /// </summary>
        internal static string Tests_VE_TestValidation_User_Erreur2 {
            get {
                return ResourceManager.GetString("Tests_VE_TestValidation.User:Erreur2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom de la propriété ne passant pas la validation.
        /// </summary>
        internal static string Tests_VE_TestValidation_User_Property {
            get {
                return ResourceManager.GetString("Tests_VE_TestValidation.User.Property", resourceCulture);
            }
        }
    }
}
