//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A3.Shared.WebApi.Core.Users {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UserResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("A3.Shared.WebApi.Core.Users.UserResources", typeof(UserResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion des utilisateurs.
        /// </summary>
        public static string Users_DefaultContextLabel {
            get {
                return ResourceManager.GetString("Users.DefaultContextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les informations de connexion sont incorrectes..
        /// </summary>
        public static string Users_PE_UserSignIn_IncorrectSignInInformation {
            get {
                return ResourceManager.GetString("Users_PE_UserSignIn.IncorrectSignInInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connexion d&apos;un utilisateur.
        /// </summary>
        public static string Users_PE_UserSignIn_Title {
            get {
                return ResourceManager.GetString("Users_PE_UserSignIn.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Des erreurs de validation ont été rencontré au moment de l&apos;enregistrement d&apos;un utilisateur..
        /// </summary>
        public static string Users_VE_UserValidation_Detail {
            get {
                return ResourceManager.GetString("Users_VE_UserValidation.Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enregistrement d&apos;un utilisateur.
        /// </summary>
        public static string Users_VE_UserValidation_Title {
            get {
                return ResourceManager.GetString("Users_VE_UserValidation.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le nom de l&apos;utilisateur contient des cara interdit..
        /// </summary>
        public static string Users_VE_UserValidation_UserName_BadFormat {
            get {
                return ResourceManager.GetString("Users_VE_UserValidation.UserName:BadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le nom de l&apos;utilisateur doit être renseigné..
        /// </summary>
        public static string Users_VE_UserValidation_UserName_Empty {
            get {
                return ResourceManager.GetString("Users_VE_UserValidation.UserName:Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom de l&apos;utilisateur.
        /// </summary>
        public static string Users_VE_UserValidation_UserName_Property {
            get {
                return ResourceManager.GetString("Users_VE_UserValidation.UserName.Property", resourceCulture);
            }
        }
    }
}
