name: Build & Test

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use .Net Core 6.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      - name: dotnet build & test
        working-directory: back\Cycle1.WebApi
        run: |
          dotnet build Cycle1.WebApi.sln
          dotnet test Cycle1.WebApi.sln
