name: .Net Core - Build & Test

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use .Net Core 6.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      - name: Install dependencies
        working-directory: back/Cycle1.WebApi
        run: dotnet restore Cycle1.WebApi.sln

      - name: Build
        working-directory: back/Cycle1.WebApi
        run: dotnet build Cycle1.WebApi.sln --configuration Release --no-restore

      - name: Test
        working-directory: back/Cycle1.WebApi
        run: dotnet test Cycle1.WebApi.sln --no-restore --verbosity normal
