name: .Net Core - Build & Test

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use .Net Core 6.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      - name: dotnet build & test
        run: dotnet build back/Cycle1.WebApi/Cycle1.WebApi.sln
