name: .Net Core - Build & Test Coverage & Sonar

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Sonarscanner for dotnet
        uses: Secbyte/dotnet-sonarscanner@v2.3
        working-directory: back\Cycle1.WebApi
        with:
          buildCommand: dotnet build Cycle1.WebApi.sln
          testCommand: dotnet test Cycle1.WebApi.sln --collect:"XPlat Code Coverage" -r ./TestsResult
          projectKey: a3-dev-team_lea
          projectName: lea
          sonarOrganisation: a3-dev-team
          beginArguments: >
            /d:sonar.verbose="true"
            /d:sonar.cs.cobertura.reportsPaths='".TestResuts/**/coverage.cobertura.xml"'
            /d:sonar.coverage.exclusions='"**/*Tests.cs","**/*.md"'
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
