name: Build & Test
on:
  workflow_dispatch:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: npm ci
        run: npm ci
      - name: npm build
        run: npm run build:push --if-present
      - name: npm test
        run: npm run test:push --if-present