name: Deploy to Azure Test

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  check-angular:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '#release') }}

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
   
      - name: npm ci
        working-directory: front
        run: npm ci

      - name: npm build 
        working-directory: front
        run: npm run build:ci     

      - name: npm test 
        working-directory: front
        run: npm run test:ci          

  check-dotnet_core:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '#release') }}

    steps:
      - uses: actions/checkout@v3

      - name: Use .Net Core 6.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      - name: install dependencies
        working-directory: back/Cycle1.WebApi
        run: dotnet restore Cycle1.WebApi.sln

      - name: dotnet build
        working-directory: back/Cycle1.WebApi
        run: dotnet build Cycle1.WebApi.sln --configuration Release --no-restore

      - name: dotnet test
        working-directory: back/Cycle1.WebApi
        run: dotnet test Cycle1.WebApi.sln --no-restore --verbosity normal

  publish :
    runs-on: ubuntu-latest
    needs: [check angular, check .Net Core]
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.JOBELIX_TOKEN }}

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: setup git config
        run: |
          # setup the username and email. Here : 'GitHub Actions Bot' with no email by default
          git config user.name "jo-belix"
          git config user.email "jo.belix@outlook.fr"

      - name: npm ci & build
        working-directory: front
        run: |
          npm ci
          npm version prerelease
          npm run build:ci -- --output-path ../release/wwwroot 

      - name: dotnet publish
        working-directory: back/Cycle1.WebApi
        run: dotnet publish Cycle1.WebApi.sln --configuration Release --no-restore --output ../../release/

      - name: commit version updated
        working-directory: front
        run: |
          # Stage the file, commit and push
          git add package.json
          git commit -m "#release"
          git push

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: lea-app
          path: ./release/

  deploy:
    runs-on: ubuntu-latest
    needs: build_test_publish
    environment:
      name: "test"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: lea-app

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "lea-a3-test"
          slot-name: "production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_TEST }}
          package: .
