name: Deploy to Azure Test

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  build & test front:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: npm ci, build & test
        working-directory: front
        run: |
          npm ci
          npm run build:ci -- --output-path ../release/wwwroot --if-present
          npm run test:ci --if-present

 build & test & publish back:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use .Net Core 6.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      - name: Install dependencies
        working-directory: back/Cycle1.WebApi
        run: dotnet restore Cycle1.WebApi.sln

      - name: Build
        working-directory: back/Cycle1.WebApi
        run: dotnet build Cycle1.WebApi.sln --configuration Release --no-restore

      - name: Test
        working-directory: back/Cycle1.WebApi
        run: dotnet test Cycle1.WebApi.sln --no-restore --verbosity normal

      - name: Publish
        working-directory: back/Cycle1.WebApi
        run: dotnet publish Cycle1.WebApi.sln --configuration Release --no-restore --output ../../release/

 upload :
    runs-on: ubuntu-latest

    steps:
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: lea-app
          path: ./release/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Test"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: lea-app

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "lea-a3"
          slot-name: "Production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: .
